### ISSUE TITLE
[Q] Basic Auth 

### ISSUE THREAD

**Issue by yorci** [wordpress-clients/wp-api-angular#21]
Hi, how can i use basic auth with that library? 

i tried that: 

```
header = new Headers({"Authorization":"Basic [BASE64_STRING]"});
this.wpApiPosts.getList({ headers:header }).toPromise()
.then(r => r.json())
.then(b => { ... })

````
also tried to pass {header} to getList method its not working also. 

but it is not working for me, or i am doing something wrong?

**Comment by shprink** [comment]
Not sure but yes I think basic auth is doable. It was built in for AngularJS version https://github.com/shprink/wp-api-angular/blob/v2.0.0-rc3/lib/Provider.js#L86-L89

I hope this help.
I will soon explore the auth with JWT as I will need it for https://github.com/shprink/wordpress-hybrid-client

let's keep this issue open

**Comment by yorci** [comment]
@shprink it isnt working on browser with ionic serve command, but its working for release build.

**Comment by fidoafif** [comment]
@yorci did you solved this? I had the same issue

**Comment by shprink** [comment]
do you run `ionic serve`? It works for me, can you be more specific on what's not working?

**Comment by fidoafif** [comment]
@shprink I run on my device and get error "unauthorized" on log

**Comment by shprink** [comment]
looks ok. Maybe basic auth is not supported anymore. I cannot see it in the docs: https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/

Have you tried to contact them?
