### ISSUE TITLE
Angular 4+ compatibility

### ISSUE THREAD

**Issue by klihelp** [wordpress-clients/wp-api-angular#24]
use:
```import { Response,RequestOptionsArgs } from '@angular/http';```

instead:
```
import { RequestOptionsArgs } from '@angular/http/src/interfaces';
import { Response } from '@angular/http/src/static_response';
```

**Comment by shprink** [comment]
OMG, the rest is ok? How about `OpaqueToken` ?

**Comment by klihelp** [comment]
No error for OpaqueToken, but tons of other incompatibilities errors like:
```
Namespace ''*'' has no exported member 'NgModuleFactory'
Namespace ''*'' has no exported member 'Injector'
Type 'any' is not a constructor function type
Property 'parent' does not exist on type 'WpApiModuleInjector
...
```
Angular 4 is coming out in a week. They say it can be a straight replacement for Angular 2.
A good read,
https://jaxenter.com/road-angular-4-rc3-131386.html

**Comment by shprink** [comment]
link is 404

**Comment by klihelp** [comment]
it is, reading link is 404.
did you caught the errors?

**Comment by klihelp** [comment]
Dependency update for both Angular 2 and 4 would be good.

**Comment by shprink** [comment]
I updated to ng4 and it works. can you confirm too?

**Comment by klihelp** [comment]
Can't see any commit..

**Comment by shprink** [comment]
I have not commited anything. I upgraded to ng4 and the lib works. Does it work too on your side?
The only thing that bothers you is the dependencies version?

**Comment by krokofant** [comment]
It seems to work for me with ng4 but the factory example gave me an error:
![image](https://cloud.githubusercontent.com/assets/5908498/24582162/249931c8-172a-11e7-88ce-64d119bcd17f.png)

I just mindlessly set the type to `any` instead.

**Comment by klihelp** [comment]
Tomorrow I feedback my test.

**Comment by brunetgarcia** [comment]
OpaqueToken is Deprecated in ng4
https://angular.io/docs/ts/latest/api/core/index/OpaqueToken-class.html

**Comment by shprink** [comment]
yes it is but it is not removed yet so v4 should be fine. It is fine on my side.

**Comment by klihelp** [comment]
Works with Angular 4 with current dependencies.

**Comment by klihelp** [comment]
`Warning: Can't resolve all parameters for Custom in /www/ks-com/content/themes/kli-ng-sr/node_modules/wp-api-angular/Custom.d.ts: ([object Object], [object Object], ?). This will become an error in Angular v5.x`

**Comment by klihelp** [comment]
@krokofant update package.json to Angular 4, and remove @ angular  from wp-api-angular/node_modules

**Comment by shprink** [comment]
those upgrade every 6 months are killing me!

**Comment by hyperpress** [comment]
But Angular 4 fixes a lot of issues that 1 and 2 suffered from, and my understanding is 4 is slotted to be an LTS version. So, you should be good to go for awhile ;-)

**Comment by shprink** [comment]
PRs to make it work with ng4+ are more than welcome people :)

**Comment by shprink** [comment]
beta8 should fix any errors with Angular4, please re open if you see any problem. I tested with AOT on Ionic 3 and Angular 4 via the CLI.
