### ISSUE TITLE
ERROR on 'ng build --prod'

### ISSUE THREAD

**Issue by metazoa-org** [wordpress-clients/wp-api-angular#26]
The compilled error is as follows (running ng build --prod):
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Library/WebServer/Documents/dev/sites/solsol.cz/webapp/solsol/node_modules/**wp-api-angular**/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /Library/WebServer/Documents/dev/sites/solsol.cz/webapp/solsol/node_modules/**wp-api-angular**/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in /Library/WebServer/Documents/dev/sites/solsol.cz/webapp/solsol/node_modules/**wp-api-angular**/node_modules/@angular/core/src/di/opaque_token.d.ts

**Comment by shprink** [comment]
beta8 should fix any errors with Angular4, please re open if you see any problem. I tested with AOT on Ionic 3 and Angular 4 via the CLI.
