### ISSUE TITLE
use of nonce

### ISSUE THREAD

**Issue by ceda018** [wordpress-clients/wp-api-angular#30]
I'm writing WP plugin with Angular  (4)  and want to use Cookie auth.  How can I get valid nonce for HTTP request header 'X-WP-Nonce'?

I've tried to send new nonce with PHP header(), and wp_create_nonce() so that I can use it with new GET request from front-end, but this nonce is not valid when request is sent.

How can I get valid nonce for request like /wp/v2/users/me ?

Thank you.

**Comment by shprink** [comment]
If you want to log in from a JS client you should check out WP JWT plugin, once you get the token, I guess you will only need to had it into the header request to make it work.

**Comment by ceda018** [comment]
This is the scenario I want to implement:
1. Log in via regular WP login form,
2. after successful login, if subscriber (customer), my plugin redirects to the custom post type which will load the template with Angular 4 Single Page Application (SPA).
3. From this SPA I want to send GET or POST requests with Cookie authentication, so I need to have nonce in header in order not to have 401 Forbidden ( invalid nonce)  

So, I have WP Cookie but don't have wp_nonce.  

wp-api  enqueued from the back-end works well, so I can make request from Chrome Dev Console ( var b = new wp.api.models.UsersMe; b.fetch(); ) , and take from the Request Header: X-WP-Nonce:8ec95ee8ed value,  hard code to SPA ( nonce is valid 12 or 24 hrs), and my HTTP requests from SPA works.

I can send from template PHP header('my_nonce', wp_create_nonece())  but this is different nonce that won't work with current cookie, so the requests are 401 Forbidden.

How can I get current nonce?

**Comment by shprink** [comment]
No idea

**Comment by ceda018** [comment]
Ok, thank you for your time.

**Comment by ceda018** [comment]
I didn't understand what 'action' 'wp_rest' means in wp_create_nonce(), but now with $my_nonce = wp_create_nonce( 'wp_rest' ); I have correct nonce which I can use for cookie auth. Requests with nonce validation  works now. :)
