### ISSUE TITLE
[Doc/Feature] WP Query params RequestOptionsArgs?

### ISSUE THREAD

**Issue by mattbag** [wordpress-clients/wp-api-angular#32]
Hello, 
is there a way to query the wp parameters with RequestOptionsArgs?
As in changing the defaults, e.g. posts will get me 10 latest posts.

If you could add an example in the docs that would be nice, cheers

**Comment by shprink** [comment]
I think the demo will help you with that: https://plnkr.co/edit/hqE4bvbM6HXql5Insjx8?p=preview

**Comment by shprink** [comment]
actually this might be better: https://github.com/wordpress-clients/wp-api-angular/issues/18

```ts
import { URLSearchParams } from '@angular/http';
export class Component {
    constructor(
        private wpApiPages: WpApiPages
    ) { }

    getPageBySlug() {
        const uRLSearchParams = new URLSearchParams();
        uRLSearchParams.set('slug', 'about');

        wpApiPages.getList(
            search: uRLSearchParams
        ).map((r) => r.json())
        .subscribe(()
    }
}
```
