### ISSUE TITLE
Unable to implement infinite scrolling

### ISSUE THREAD

**Issue by rohitvishal7** [wordpress-clients/wp-api-angular#36]
I am trying to implement infinite scrolling to get posts automatically when the user gets to the last post on the page. Trying this while building an ionic android app.

**Comment by shprink** [comment]
Ionic as a infinite scroll component. https://github.com/wordpress-clients/hybrid uses this lib and this component to load posts. Example: https://wordpress-clients.github.io/hybrid/#/posts
