### ISSUE TITLE
Support Angular 7

### ISSUE THREAD

**Issue by stephengardner** [wordpress-clients/wp-api-angular#45]
As noted: `Package "wp-api-angular" has an incompatible peer dependency to "@angular/http" (requires ">=5.0.0-rc.0 <6.0.0||>=4.0.0 <5.0.0", would install "7.0.4").`

**Comment by aharl** [comment]
Is this project dead?

**Comment by shprink** [comment]
yeah it is dead, you can fork and upgrade, it should work.

**Comment by angus151** [comment]
> yeah it is dead, you can fork and upgrade, it should work.

Any reason in particular this project died? 

Any recommendations on other projects or CMS's to use instead?

**Comment by shprink** [comment]
It is dead because it needs constant changes. Angular major changes every 6 months and WP-API used to change often as well.

It is hell to maintain. You can fork and do whatever you need with it.

sorry
